services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # Port standard pour l'API AMQP
      - "15672:15672" # Port de l'interface de gestion web | Web management UI
      - "15692:15692"  # Prometheus metrics
    environment:
      - RABBITMQ_DEFAULT_USER=user     # Utilisateur par défaut
      - RABBITMQ_DEFAULT_PASS=password # Mot de passe par défaut
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_prometheus
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  rabbitmq_data:
  grafana_data: