services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5673:5672"   # Port standard pour l'API AMQP
      - "15673:15672" # Port de l'interface de gestion web | Web management UI
      - "15692:15692"  # Prometheus metrics
    environment:
      - RABBITMQ_DEFAULT_USER=user     # Utilisateur par défaut
      - RABBITMQ_DEFAULT_PASS=password # Mot de passe par défaut
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_prometheus
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  rabbitmq_data:
  grafana_data:

  # Microservices backend
  # group_ms:
  #   build: ./backend/group_ms
  #   container_name: group_ms
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ehei-network

  # messagerie_ms:
  #   build: ./backend/messagerie_ms
  #   container_name: messagerie_ms
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ehei-network

  # notification_ms:
  #   build: ./backend/notification_ms
  #   container_name: notification_ms
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ehei-network

  # publication_ms:
  #   build: ./backend/publication_ms
  #   container_name: publication_ms
  #   ports:
  #     - "3003:3003"
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ehei-network

  # recherche_ms:
  #   build: ./backend/recherche_ms
  #   container_name: recherche_ms
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ehei-network

  # utilisateur_ms:
  #   build: ./backend/utilisateur_ms
  #   container_name: utilisateur_ms
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ehei-network

  # Frontend
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   # depends_on:
  #   #   - publication_ms
  #   #   - utilisateur_ms
  #   #   - notification_ms
  #   networks:
  #     - ehei-network

# volumes:
#   rabbitmq_data:
#   grafana_data:

# networks:
#   ehei-network:
#     driver: bridge
